version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/ContactManagerMERN/
hooks:
  AfterInstall:
    - location: /var/www/ContactManagerMERN/build_reactjs.sh
      timeout: 60
      runas: root
