version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/ContactManagerDeployment/
hooks:
  AfterInstall:
    - location: /var/www/ContactManagerApp/build_reactjs.sh
      timeout: 60
      runas: root
