version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/ContactManagerMERN/
    overwrite: true
hooks:
  AfterInstall:
    - location: /var/www/ContactManagerMERN/build_reactjs.sh
      timeout: 30
      runas: root
